webproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

webproject/tokyo03/urls.py
from django.urls import path
from . import views
from .views import Listtokyo03View,RecommendationView

urlpatterns = [
    path('', Listtokyo03View.as_view(), name='list_tokyo03'),
    path('Recommendation/<int:pk>/',RecommendationView.as_view(), name='recommendation-detail'),
    ]

webproject/webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from tokyo03.views import Listtokyo03View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Listtokyo03View.as_view(), name='list_tokyo03'),  # 追加する行
    path('tokyo03/', include('tokyo03.urls')),
]

webproject/accounts/models.py
from django.db import models

# Create your models here.

webproject/tokyo03/models.py
from django.db import models

# Create your models here.
from django.db import models

class Special(models.Model):
    title = models.CharField(max_length = 30)
    text = models.TextField()
    thumbnail = models.ImageField()

webproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

webproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView


from  .forms import SignupForm
# Create your views here.

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name='accounts/signup.html'
    success_url = reverse_lazy('index')

webproject/tokyo03/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView
from .models import Special

class Listtokyo03View(ListView):
    template_name = 'tokyo03/index.html'
    model = Special

class RecommendationView(DetailView):  
    template_name = 'tokyo03/recommendation.html'
    model = Special

webproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}


{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}
{% block content %}
    <form method="post" class="m-4 bg-light border border-success rounded from-group">
        {% csrf_token %}
        <input type="text" name='username' class="form-control my-4"placeholder="ユーザー ID" >
        <input type="password" name='password' class="form-control mt-4"placeholder="パスワード" >
        <input type="password" name='password2' class="form-control m4-4"placeholder="パスワード確認用" >
        <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください</small>
        {% if form.errors %}
            <span class="mb-2 small text-danger d-block text-start">利用できないユーザー IDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
        {% endif %}
        <button type="submit" class="btn btn-success m-2">アカウント作成</button>
    </form>
{% endblock %}        

webproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>東京03紹介サイト</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<link rel="stylesheet" href="{% static 'tokyo03/css/style.css' %}">
</head>

<body class="home">

    <div class="navbar-nav d-flex flex-row">
        {% if request.user.is_authenticated %}
        <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
         <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
         <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>

         {% endif %}
    </div>     
<div id="container">

<header>
    {% block header %}{% endblock %}
</header>

{% block content %}{% endblock %}
<footer>
    <small>Copyright&copy; <a href="index.html">Artist Name</a> All Rights Reserved.</small>
    <span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
    </footer>
    
    <!--ページの上部へ戻るボタン-->
    <div class="pagetop"><a href="#"><i class="fas fa-angle-double-up"></i></a></div>
    
    </div>
    <!--/#container-->
    
    <!--開閉ブロック-->
    <div id="menubar">
    
    <nav>
    <ul>
    <li><a href="index.html">ホーム</a></li>
    <li><a href="profile.html">プロフィール</a></li>
    <li><a href="portfolio.html">作品集</a></li>
    <li><a href="contact.html">お問い合わせ</a></li>
    <li><a href="link.html">リンク集</a></li>
    </ul>
    </nav>
    
    <ul class="icon">
    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
    <li><a href="#"><i class="fab fa-line"></i></a></li>
    <li><a href="#"><i class="fab fa-youtube"></i></a></li>
    </ul>
    
    </div>
    <!--/#menubar-->
    
    <!--開閉ボタン（ハンバーガーアイコン）-->
    <div id="menubar_hdr">
    <span></span><span></span><span></span>
    </div>
    
    <!--jQueryの読み込み-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
    <!--パララックス（inview）-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
    <script src="{% static 'tokyo03/js/jquery.inview_set.js' %}"></script>
    
    <!--このテンプレート専用のスクリプト-->
    <script src="{% static 'tokyo03/js/main.js' %}"></script>
    
    
    </body>
    </html>

webproject/tokyo03/templates/tokyo03/03.html
<!DOCTYPE html>
<html lang="ja">
        <head>
                <meta charset="UTF-8">
                <link rel="stylesheet" href=reset.css>
                <link rel="stylesheet" href=03.css>
        </head>
        <body>
            東京03紹介サイト
        <div class="header">
            <p>member</p>
            <p>About</p>
            <p>youtube</p>
        </div>
        <p>member</p>
        <div class="iiduka">
            <p>飯塚 悟志（いいづかさとし）</p>
                東京03のリーダー<br>
                スクールJCA2期生<br>
                生年月日:S.48.5.27生<br>
                出身地：千葉県四街道市<br>
                血液型:O型<br>
                サイズ:T.170cm/W.60kg<br>
                四街道市立南小学校、四街道市立千代田中学校を経て、<br>
                千葉県立若松高等学校卒業。<br>
                プロダクション人力舎所属。<br>
                1995年、豊本明長とお笑いコンビ、「アルファルファ」を結成<br>
                2003年、アルファルファに元プラスドライバーの角田晃広を<br>
                加入させる形で、「東京03」を結成。<br>
                <img src="iiduka.jpg"alt = "飯塚">
            </p>
        <div class="kakuta">
            <p>角田 晃広（かくたあきひろ）
                    生年月日:S.48.12.13生<br>
                    出身地：東京都<br>
                    血液型:A型<br>
                    サイズ:T.172cm/W.62kg<br>
                    趣味：弾き語り<br>
                    特技：卓球<br>
                    ハイテンションなボケが特徴。<br>
                    コント内ではヘタレで見栄っ張りなキャラを演じることが多く、<br>
                    稀に女装をする<br>
                    <img src="kakuta.jpg">
            </p>
        <div class="toyomoto">
            <p>豊本 明長（とよもとあきなが）
                スクールJCA:スクールJCA3期生<br>
                生年月日:S.50.6.6生<br>
                出身地：愛知県<br>
                血液型:A型<br>
                サイズ:T.175cm/W.65kg<br>
                趣味：音楽<br>
                特技：プロレス観戦<br>
                屈託のない飄々としたキャラが特徴。出番・セリフが相方2人に比べて少ないが、女性役はほとんど豊本が担当している。<br>
                名前は豊本豊美<br>
                相方2人に比べると不気味でミステリアスな<br>
                雰囲気を醸し出す役回りを演じる事も多く、<br>物語の核を担う事も多くある。<br>
                個人的にはネタの中心は豊本が担っていると考える。<br>
                <img src="toyomoto.jpg">
            </p> 
        </div>
        <p>about</p>  
            <div class="about"> 
                <img src="live.jpg">    
                <p1><br>飯塚は学生時代からお笑いが好きで、学園祭など人前で披露するわけでもなくネタを書いていたという。<br>
                    高校卒業後の進路で就職か大学進学かで悩んでいた1992年、<br>ノストラダムスの大予言が流行。10年もしない内に世界が滅ぶなら好きなことをしようと内向的な性格ながらも芸人を志す。<br>
                    また、豊本も高校卒業後の進路で悩み、就職も大学進学も嫌だったためお笑いは楽しそうで上京もできると考え、<br>芸人を目指して養成所に入ることとなる。<br>
                    スクールJCA2期生だった飯塚は通った1年間で相方を見つけられず、3期生で当時別のコンビにて活動しツッコミを担当していた豊本を誘いコンビ『アルファルファ』を1995年に結成。<br>
                    <img src="a.jpg">
                </p1>
                <p2>
                    <br>日常に潜む「何気ないシチュエーション」を描いた<br>究極のリアル系コント<br>
                    トリオ名は3人組であること2003年に結成したこと東京23区の<br>市外局番をかけたトリプルネーミングである。<br>
                <img src="ossann.jpg">
                <br>最初期のコントについては飯塚と角田の
                2人で作っており、<br>豊本はネタ作りに参加していない。<br>
                角田が出した設定で書くこともあれば、飯塚が考えた設定で角田が<br>
                自分のセリフを書くこともあったが、<br>
                すぐに飯塚が殆どのシナリオを書くようになり飯塚は「結成当初は2人で完全に半々でやってたんですけど、すぐに僕の負担が大きくなって…」と述べている。<br>
                また、それを受けた角田は「その方が面白いネタが出来上がるんでね！」と語っている<br>  
                </p2>
            </div>
            <div class="Youtube">
                <img src="icon.png">
                <p>おすすめの動画</p>
                <a href="https://www.youtube.com/watch?v=rWhym_XHmtc">
                <img src="marry.jpg">
                </a>
                <a1><br>新郎と友人</a1><br>
                <p1>
                    東京03の「新郎と友人」は、2022年2月24日に開催された第18回東京03単独公演「明日の風に吹かれないで」で披露されたコントです。
                    このコントは、結婚式場の控室でうなだれる新郎の角田に友人2人が接する内容で、東京03っぽくないコントというテーマで披露されました。
                </p1>
                <a href="https://www.youtube.com/watch?v=jIhTwXqUDwU">
                <img src="are.jpg">
                </a>
                <a2><br>豊本のアレ</a2>
                <p2>
                「トヨモトのアレ」は、2003年の第19回単独公演「自己泥酔」で披露されたコントです。
                豊本さんの浮気がバレたときに飯塚さんが...という内容です。
                </p2>
                <a href="https://www.youtube.com/watch?v=2mQI5pO8Gmw&t=24s">
                <br><img src="bardwatching.jpg">
                </a>
                <a3><br>バードウォッチング</a3>
                <p>
                    東京03の「バードウォッチング」は、2018年7月8日から10月14日に開催された第20回単独公演「不自然体」で披露されたコントです。
                    飯塚が「やりたいこと公演」で披露したネタで、15年ほど前から演じているそうです。
                    <em>「バードウォッチング」は、初心者にいい格好を見せようとしている角田さんがどんどん追い込まれていく内容です。</em>
                </p>
                <a href="https://www.youtube.com/watch?v=YSaF6Fz1-bA&t=8s">
                <img src="koshibai.jpg">
                </a>
                <a4><br>センスなき故に</a4>
                <p4>
                    「センスなき故に」は、お笑い芸人東京03の2022年2月24日公演「あるがままの君でいないで」で披露されたコントです。
                    このコントは、料理の注文センスで言い争う3人が大騒動に巻き込まれる内容で、東京追加公演のみで披露されました。

                </p4> 
                <footer>
                    <p>Twitter</p>
                    <a1 href="https://twitter.com/kakuta_tokyo03">角田晃広</a><br>
                    <a2 href="https://twitter.com/iizuka03">飯塚悟志</a><br>
                    <a3 href="https://twitter.com/toyo03">豊本明長</a><br>
                    <a href="https://apps.apple.com/jp/app/tokyo-03-company-%E6%9D%B1%E4%BA%AC03%E3%82%AA%E3%83%95%E3%82%A3%E3%82%B7%E3%83%A3%E3%83%AB%E3%82%A2%E3%83%97%E3%83%AA/id1328847843">東京03オフィシャルアプリ東京03Company
        </body>
    </html>

webproject/tokyo03/templates/tokyo03/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>アーティスト(画家・作家・音楽家など)向け 無料ホームページテンプレート tp_artist1</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<link rel="stylesheet" href="css/style.css">
</head>

<body>

<div id="container">

<header>
<h1 id="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}" alt="Artist Name"></a></h1>
</header>

<div id="contents">

<main>

<section>

<h2 class="c">Contact<span>お問い合わせ</span></h2>
<p class="c">Instagramのプロフィールページからお問い合わせ下さい。<br>
（※例です）</p>

</section>

</main>

</div>
<!--/#contents-->

<footer>
<small>Copyright&copy; <a href="index.html">Artist Name</a> All Rights Reserved.</small>
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</footer>

<!--ページの上部へ戻るボタン-->
<div class="pagetop"><a href="#"><i class="fas fa-angle-double-up"></i></a></div>

</div>
<!--/#container-->

<!--開閉ブロック-->
<div id="menubar">

<nav>
<ul>
<li><a href="index.html">ホーム</a></li>
<li><a href="profile.html">プロフィール</a></li>
<li><a href="portfolio.html">作品集</a></li>
<li><a href="contact.html">お問い合わせ</a></li>
<li><a href="link.html">リンク集</a></li>
</ul>
</nav>

</div>
<!--/#menubar-->

<!--開閉ボタン（ハンバーガーアイコン）-->
<div id="menubar_hdr">
<span></span><span></span><span></span>
</div>

<!--jQueryの読み込み-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!--パララックス（inview）-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
<script src="js/jquery.inview_set.js"></script>

<!--このテンプレート専用のスクリプト-->
<script src="js/main.js"></script>

</body>
</html>
{% endblock content %}              

webproject/tokyo03/templates/tokyo03/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<h1 id="logo"><img src="{% static 'tokyo03/images/icon.png' %}" alt="Artist Name"></a></h1>
<link rel="stylesheet" href="{% static 'tokyo03/css/style.css' %}">


{% endblock %}

{% block content %}
<div id="contents">

<main>

<section class="blur">

<h2>東京03紹介サイト<span></span></h2>

<h3>Member</h3>
    <p>
     飯塚 悟志（いいづかさとし）
     東京03のリーダー<br>
     スクールJCA2期生<br>
     生年月日:S.48.5.27生<br>
     出身地：千葉県四街道市<br>
     血液型:O型<br>
     サイズ:T.170cm/W.60kg<br>
     四街道市立南小学校、四街道市立千代田中学校を経て、<br>
     千葉県立若松高等学校卒業。<br>
     プロダクション人力舎所属。<br>
     1995年、豊本明長とお笑いコンビ、「アルファルファ」を結成<br>
     2003年、アルファルファに元プラスドライバーの角田晃広を<br>
     加入させる形で、「東京03」を結成。<br>
     </p>
     <div class="i">
        <img src="{% static 'tokyo03/images/satoshi.jpeg' %}"alt = "飯塚">
    </div>
    <p>
        角田 晃広（かくたあきひろ）<br>
        生年月日:S.48.12.13生<br>
        出身地：東京都<br>
        血液型:A型<br>
        サイズ:T.172cm/W.62kg<br>
        趣味：弾き語り<br>
        特技：卓球<br>
        ハイテンションなボケが特徴。<br>
        コント内ではヘタレで見栄っ張りなキャラを演じることが多く、<br>
        稀に女装をする<br>
        <div class="m">
            <img src="{% static 'tokyo03/images/miki.jpeg' %}"alt="角田">
        </div>
    </p>
    <p>
        豊本 明長（とよもとあきなが）
        スクールJCA:スクールJCA3期生<br>
        生年月日:S.50.6.6生<br>
        出身地：愛知県<br>
        血液型:A型<br>
        サイズ:T.175cm/W.65kg<br>
        趣味：音楽<br>
        特技：プロレス観戦<br>
        屈託のない飄々としたキャラが特徴。出番・セリフが相方2人に比べて少ないが、女性役はほとんど豊本が担当している。<br>
        名前は豊本豊美<br>
        相方2人に比べると不気味でミステリアスな<br>
        雰囲気を醸し出す役回りを演じる事も多く、<br>
        <strong>全てのコントで物語の核を担っている。<br></strong>
        長いセリフが多い時もある。<br>
        <div class="t">
            <img src="{% static 'tokyo03/images/nametageru.jpeg' %}"alt="トヨモティーノ舐めたげる">
        </div>
    </p> 
<h3></h3>
<p><a href="{% static 'tokyo03/images/about.html"></a></p>

</section>

<div class="about"> 
    <img src="{% static 'tokyo03/images/live.jpg' %}">    
    <p1><br>飯塚は学生時代からお笑いが好きで、学園祭など人前で披露するわけでもなくネタを書いていたという。<br>
        高校卒業後の進路で就職か大学進学かで悩んでいた1992年、ノストラダムスの大予言が流行。10年もしない内に世界が滅ぶなら好きなことをしようと内向的な性格ながらも芸人を志す。<br>
        また、豊本も高校卒業後の進路で悩み、就職も大学進学も嫌だったためお笑いは楽しそうで上京もできると考え、芸人を目指して養成所に入ることとなる。<br>
        スクールJCA2期生だった飯塚は通った1年間で相方を見つけられず、3期生で当時別のコンビにて活動しツッコミを担当していた豊本を誘いコンビ『アルファルファ』を1995年に結成。<br>
        <img src="{% static 'tokyo03/images/a.jpg' %}">
    </p1>
    <p2>
        <br>日常に潜む「何気ないシチュエーション」を描いた究極のリアル系コント<br>
        <strong>トリオ名は3人組であること2003年に結成したこと東京23区の市外局番をかけたトリプルネーミングである。<br></strong>
    <img src="{% static 'tokyo03/images/ossann.jpg' %}">
    <br>最初期のコントについては飯塚と角田の
    2人で作っており、豊本はネタ作りに参加していない。<br>
    角田が出した設定で書くこともあれば、飯塚が考えた設定で角田が
    自分のセリフを書くこともあったが、<br>
    すぐに飯塚が殆どのシナリオを書くようになり飯塚は「結成当初は2人で完全に半々でやってたんですけど、すぐに僕の負担が大きくなって…」と述べている。<br>
    また、それを受けた角田は「その方が面白いネタが出来上がるんでね！」と語っている<br>  
    </p2>
</div>

<section class="blur">

<h2 class="c">youtube<span></span></h2>

<div class="list-banner">

    
<a href="{% url 'recommendation-detail' pk=1 %}">
<div class="list">
<h4>おすすめ動画<span></span></h4>
<figure><img src="{% static 'tokyo03/images/1.jpg' %}" alt=""></figure>
</div>
</a>

<a href="https://www.p-jinriki.com/talent/tokyo03/">
<div class="list">
<h4>東京03公式サイト<span></span></h4>
<figure><img src="{% static 'tokyo03/images/2.jpg' %}" alt=""></figure>
</div>
</a>

</div>

</section>

<div id="menubar">

    <nav>
    <ul>
    <li><a href="index.html">home</a></li>
    <li><a href="profile.html">プロフィール</a></li>
    <li><a href="reccomendation.html">作品集</a></li>
    <li><a href="contact.html">お問い合わせ</a></li>
    <li><a href="link.html">リンク集</a></li>
    </ul>
    </nav>
    
    </div>

</main>

</div>
<!--/#contents-->
{% endblock %}

webproject/tokyo03/templates/tokyo03/link.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>アーティスト(画家・作家・音楽家など)向け 無料ホームページテンプレート tp_artist1</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<link rel="stylesheet" href="css/style.css">
</head>

<body>

<div id="container">

<header>
<h1 id="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}" alt="Artist Name"></a></h1>
</header>

<div id="contents">

<main>

<section>

<h2 class="c">Link<span>リンク集</span></h2>

<table class="ta1">
<tr>
<th><a href="#">サイト名</a></th>
<td>ここに内容を入れます。サンプルテキスト。</td>
</tr>
<tr>
<th><a href="#">サイト名</a></th>
<td>ここに内容を入れます。サンプルテキスト。</td>
</tr>
<tr>
<th><a href="#">サイト名</a></th>
<td>ここに内容を入れます。サンプルテキスト。</td>
</tr>
<tr>
<th><a href="#">サイト名</a></th>
<td>ここに内容を入れます。サンプルテキスト。</td>
</tr>
<tr>
<th><a href="#">サイト名</a></th>
<td>ここに内容を入れます。サンプルテキスト。</td>
</tr>
</table>

</section>

</main>

</div>
<!--/#contents-->

<footer>
<small>Copyright&copy; <a href="index.html">Artist Name</a> All Rights Reserved.</small>
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</footer>

<!--ページの上部へ戻るボタン-->
<div class="pagetop"><a href="#"><i class="fas fa-angle-double-up"></i></a></div>

</div>
<!--/#container-->

<!--開閉ブロック-->
<div id="menubar">

<nav>
<ul>
<li><a href="index.html">ホーム</a></li>
<li><a href="profile.html">プロフィール</a></li>
<li><a href="portfolio.html">作品集</a></li>
<li><a href="contact.html">お問い合わせ</a></li>
<li><a href="link.html">リンク集</a></li>
</ul>
</nav>

</div>
<!--/#menubar-->

<!--開閉ボタン（ハンバーガーアイコン）-->
<div id="menubar_hdr">
<span></span><span></span><span></span>
</div>

<!--jQueryの読み込み-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!--パララックス（inview）-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script>
<script src="{% static 'js/jquery.inview_set.js' %}"></script>

<!--このテンプレート専用のスクリプト-->
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>
{% endblock content %}

webproject/tokyo03/templates/tokyo03/review_form.html
{% extends 'base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}
{% block content %}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded from-group">
        {% csrf_token %}
        <label>
            対象動画
        </label>    
        <input class="form-control" value="{{object.title}}"readonly>
        <label>
         タイトル
        </label>
        <input class="form-control" name="title">
        <label>
            本文
        </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <label>
            星の数
        </label>    
        <select class="form-control" name="rate">
            <option value="0">0 (最低)</option>    
            <option value="1">1 </option>
            <option value="2">2 </option>
            <option value="3">3 (普通) </option>
            <option value="4">4</option>
            <option value="5">5 (最高)</option>
        </select>
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    </form>
{% endblock %}        